# .github/workflows/pipeline.yml
name: Github Actions Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run tests
        run: mvn clean test

      - name: Upload Cucumber reports
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports/cucumber-html-reports/**

      - name: Prepare reports for GitHub Pages
        run: |
          mkdir -p reports
          # Copy report files to reports directory
          cp -r target/cucumber-reports/cucumber-html-reports/* reports/
          # Duplicate overview-features.html as index.html
          cp reports/overview-features.html reports/index.html
          # Add cache control headers to index.html
          sed -i '1i<meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate, max-age=0">' reports/index.html
          sed -i '2i<meta http-equiv="Pragma" content="no-cache">' reports/index.html
          sed -i '3i<meta http-equiv="Expires" content="0">' reports/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./reports
          publish_branch: gh-pages